# We're not a C# project.
build: off
cache:
  - "%LOCALAPPDATA%\\Yarn"
  - "%LOCALAPPDATA%\\pip\\cache"
environment:
  PYTHON: "C:\\Python36-x64"
  PYTHON_VERSION: "3.6.x" # currently 3.4.3
  PYTHON_ARCH: "64"
install:
  # Install Python (from the official .msi of http://python.org) and pip when
  # not already installed.
  - ps: if (-not(Test-Path($env:PYTHON))) { & appveyor\install.ps1 }

  # Prepend newly installed Python to the PATH of this build (this cannot be
  # done from inside the powershell script as it would require to restart
  # the parent CMD process).
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - ps: Install-Product node 8
  - python --version
  - pip --version
  - node --version
  - yarn --version
  - pip install --disable-pip-version-check --user --upgrade pip
  - pip install mitmproxy
  - yarn install
test_script:
  - yarn test
